### ISSUE TITLE
Code review needed

### ISSUE THREAD

**Issue by Eriwyr** [PolytechLyon/isi3-singleton-chabrier-bernier-tp5#1]
@Slashgear Bonjour, 
Nous avons push une version finalisé du TP5, nous attendons vos retours, merci d'avance :)

**Comment by BernierMaxence** [comment]
Bonjour @Slashgear, 
Merci pour vos retours. Nous avons mis à jour le rapport et ajouté l'utilisation des Profils. 
Bonne journée

**Comment by Slashgear** [comment]
👌
